server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    client-resuming:
      enabled: false
    player-update-interval: 5

plugins:
  - plugin: com.github.topi314.lavalink.spotify.SpotifyPlugin
    clientId: "88a3b988c704472d87f34122e2ad16cc"
    clientSecret: "5a71fc67626c40e695d2b6f5323772a3"
    countryCode: "US"
  - plugin: dev.lavalink.plugins.yt.YtDlpPlugin
